/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdv_dall;

/**
 *
 * @author Daniela
 */
public class FrameAbono extends javax.swing.JFrame {

    /**
     * Creates new form FrameAbono
     */
    FrameDashboard frameDashboard;
    
    public FrameAbono() {
        initComponents();
    }

    public void setDashboardFrame(FrameDashboard frameDashboard){
        this.frameDashboard = frameDashboard;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FrameAbono = new javax.swing.JLabel();
        BotonDashboard = new javax.swing.JButton();
        BotonClientes = new javax.swing.JButton();
        BotonSolicitudProveedores = new javax.swing.JButton();
        BotonProveedores = new javax.swing.JButton();
        BotonApartados = new javax.swing.JButton();
        BotonColaboradores = new javax.swing.JButton();
        BotonProductos = new javax.swing.JButton();
        BotonFactura = new javax.swing.JButton();
        BotonTienda = new javax.swing.JButton();
        BotonPedido = new javax.swing.JButton();
        TextFieldFecha = new javax.swing.JTextField();
        LabelFecha = new javax.swing.JLabel();
        BotonGuardar = new javax.swing.JButton();
        BotonImprimir = new javax.swing.JButton();
        BotonAgregar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonAbono = new javax.swing.JButton();
        LabelIDApartado = new javax.swing.JLabel();
        TextFieldIDApartado = new javax.swing.JTextField();
        LabelMontoAbono = new javax.swing.JLabel();
        TextFieldMontoAbono = new javax.swing.JTextField();
        LabelIDAbono = new javax.swing.JLabel();
        TextFieldIDAbono = new javax.swing.JTextField();
        LabelUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1150, 600));

        FrameAbono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FrameAbono.setText("Abonos");

        BotonDashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonDashboard.setText("Dashboard");
        BotonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDashboardActionPerformed(evt);
            }
        });

        BotonClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonClientes.setText("Clientes");

        BotonSolicitudProveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonSolicitudProveedores.setText("Solicitud a Proveedores");
        BotonSolicitudProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSolicitudProveedoresActionPerformed(evt);
            }
        });

        BotonProveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonProveedores.setText("Proveedores");

        BotonApartados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonApartados.setText("Apartados");
        BotonApartados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonApartadosActionPerformed(evt);
            }
        });

        BotonColaboradores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonColaboradores.setText("Colaboradores");

        BotonProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonProductos.setText("Productos");

        BotonFactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonFactura.setText("Factura");
        BotonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFacturaActionPerformed(evt);
            }
        });

        BotonTienda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonTienda.setText("Tienda");
        BotonTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTiendaActionPerformed(evt);
            }
        });

        BotonPedido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonPedido.setText("Pedido entre Tiendas");
        BotonPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPedidoActionPerformed(evt);
            }
        });

        TextFieldFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldFecha.setText("jTextField1");

        LabelFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelFecha.setText("Fecha");

        BotonGuardar.setBackground(new java.awt.Color(255, 102, 0));
        BotonGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BotonGuardar.setText("Guardar");

        BotonImprimir.setBackground(new java.awt.Color(0, 153, 102));
        BotonImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonImprimir.setForeground(new java.awt.Color(255, 255, 255));
        BotonImprimir.setText("Imprimir");

        BotonAgregar.setBackground(new java.awt.Color(51, 153, 0));
        BotonAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BotonAgregar.setText("Agregar");

        BotonModificar.setBackground(new java.awt.Color(0, 51, 255));
        BotonModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonModificar.setForeground(new java.awt.Color(255, 255, 255));
        BotonModificar.setText("Modificar");

        BotonEliminar.setBackground(new java.awt.Color(255, 0, 0));
        BotonEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BotonEliminar.setText("Eliminar");

        BotonAbono.setBackground(new java.awt.Color(153, 153, 153));
        BotonAbono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonAbono.setText("Abonos");
        BotonAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAbonoActionPerformed(evt);
            }
        });

        LabelIDApartado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIDApartado.setText("ID Apartado");

        TextFieldIDApartado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldIDApartado.setText("jTextField1");

        LabelMontoAbono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelMontoAbono.setText("Monto Abono");

        TextFieldMontoAbono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldMontoAbono.setText("jTextField1");

        LabelIDAbono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIDAbono.setText("ID Abono");

        TextFieldIDAbono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldIDAbono.setText("jTextField1");

        LabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelUsuario.setText("Usuario");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelFecha)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BotonAgregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonModificar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonEliminar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(BotonGuardar)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonImprimir)))
                                .addGap(265, 265, 265))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonDashboard)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(BotonSolicitudProveedores)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonApartados)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonAbono))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(BotonClientes)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonProveedores)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonColaboradores)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonProductos)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonFactura)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonTienda)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonPedido)
                                        .addGap(73, 73, 73)
                                        .addComponent(LabelUsuario))))
                            .addComponent(FrameAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(90, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelIDApartado)
                    .addComponent(LabelIDAbono)
                    .addComponent(LabelMontoAbono))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldMontoAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldIDAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldIDApartado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FrameAbono)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonDashboard)
                    .addComponent(BotonClientes)
                    .addComponent(BotonProveedores)
                    .addComponent(BotonColaboradores)
                    .addComponent(BotonProductos)
                    .addComponent(BotonFactura)
                    .addComponent(BotonTienda)
                    .addComponent(BotonPedido)
                    .addComponent(LabelUsuario))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonApartados)
                    .addComponent(BotonAbono)
                    .addComponent(BotonSolicitudProveedores))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFecha)
                    .addComponent(TextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldIDAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelIDAbono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIDApartado)
                    .addComponent(TextFieldIDApartado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMontoAbono)
                    .addComponent(TextFieldMontoAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGuardar)
                    .addComponent(BotonImprimir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregar)
                    .addComponent(BotonModificar)
                    .addComponent(BotonEliminar))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDashboardActionPerformed
        this.frameDashboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonDashboardActionPerformed

    private void BotonSolicitudProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSolicitudProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSolicitudProveedoresActionPerformed

    private void BotonApartadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonApartadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonApartadosActionPerformed

    private void BotonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonFacturaActionPerformed

    private void BotonTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonTiendaActionPerformed

    private void BotonPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPedidoActionPerformed

    private void BotonAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAbonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAbonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAbono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAbono;
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonApartados;
    private javax.swing.JButton BotonClientes;
    private javax.swing.JButton BotonColaboradores;
    private javax.swing.JButton BotonDashboard;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonFactura;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonImprimir;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton BotonPedido;
    private javax.swing.JButton BotonProductos;
    private javax.swing.JButton BotonProveedores;
    private javax.swing.JButton BotonSolicitudProveedores;
    private javax.swing.JButton BotonTienda;
    private javax.swing.JLabel FrameAbono;
    private javax.swing.JLabel LabelFecha;
    private javax.swing.JLabel LabelIDAbono;
    private javax.swing.JLabel LabelIDApartado;
    private javax.swing.JLabel LabelMontoAbono;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JTextField TextFieldFecha;
    private javax.swing.JTextField TextFieldIDAbono;
    private javax.swing.JTextField TextFieldIDApartado;
    private javax.swing.JTextField TextFieldMontoAbono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
