/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdv_dall;

/**
 *
 * @author Daniela
 */
public class FrameTienda extends javax.swing.JFrame {

    /**
     * Creates new form FrameTienda
     */
    FrameDashboard frameDashboard;
    
    public FrameTienda() {
        initComponents();
    }

    public void setDashboardFrame(FrameDashboard frameDashboard){
        this.frameDashboard = frameDashboard;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTienda = new javax.swing.JPanel();
        LabelUsuario = new javax.swing.JLabel();
        BotonPedidoEntreTiendas = new javax.swing.JButton();
        BotonTienda = new javax.swing.JButton();
        BotonFactura = new javax.swing.JButton();
        BotonProductos = new javax.swing.JButton();
        BotonColaboradores = new javax.swing.JButton();
        BotonProveedores = new javax.swing.JButton();
        BotonClientes = new javax.swing.JButton();
        BotonDashboard = new javax.swing.JButton();
        FrameTienda = new javax.swing.JLabel();
        LabelIDTienda = new javax.swing.JLabel();
        TextFieldIDTienda = new javax.swing.JTextField();
        LabelIDColaborador = new javax.swing.JLabel();
        TextFieldIDColaborador = new javax.swing.JTextField();
        LabelIDDireccion = new javax.swing.JLabel();
        TextFieldIDDireccion = new javax.swing.JTextField();
        BotonAgregar = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonImprimir = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        BotonSolicitudProveedores = new javax.swing.JButton();
        BotonApartados = new javax.swing.JButton();
        BotonAbono = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelTienda.setPreferredSize(new java.awt.Dimension(1150, 600));

        LabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelUsuario.setText("Usuario");

        BotonPedidoEntreTiendas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonPedidoEntreTiendas.setText("Pedido entre Tiendas");
        BotonPedidoEntreTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPedidoEntreTiendasActionPerformed(evt);
            }
        });

        BotonTienda.setBackground(new java.awt.Color(153, 153, 153));
        BotonTienda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonTienda.setText("Tienda");
        BotonTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTiendaActionPerformed(evt);
            }
        });

        BotonFactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonFactura.setText("Facturas");
        BotonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFacturaActionPerformed(evt);
            }
        });

        BotonProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonProductos.setText("Productos");

        BotonColaboradores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonColaboradores.setText("Colaboradores");

        BotonProveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonProveedores.setText("Proveedores");

        BotonClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonClientes.setText("Clientes");

        BotonDashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonDashboard.setText("Dashboard");
        BotonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDashboardActionPerformed(evt);
            }
        });

        FrameTienda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FrameTienda.setText("Tienda");

        LabelIDTienda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIDTienda.setText("ID Tienda");

        TextFieldIDTienda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldIDTienda.setText("jTextField1");

        LabelIDColaborador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIDColaborador.setText("ID del Colaborador");

        TextFieldIDColaborador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldIDColaborador.setText("jTextField1");

        LabelIDDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIDDireccion.setText("ID Dirección");

        TextFieldIDDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldIDDireccion.setText("jTextField1");

        BotonAgregar.setBackground(new java.awt.Color(51, 153, 0));
        BotonAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BotonAgregar.setText("Agregar");

        BotonGuardar.setBackground(new java.awt.Color(255, 102, 0));
        BotonGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BotonGuardar.setText("Guardar");

        BotonModificar.setBackground(new java.awt.Color(0, 51, 255));
        BotonModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonModificar.setForeground(new java.awt.Color(255, 255, 255));
        BotonModificar.setText("Modificar");

        BotonImprimir.setBackground(new java.awt.Color(0, 153, 102));
        BotonImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonImprimir.setForeground(new java.awt.Color(255, 255, 255));
        BotonImprimir.setText("Imprimir");

        BotonEliminar.setBackground(new java.awt.Color(255, 0, 0));
        BotonEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BotonEliminar.setText("Eliminar");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        BotonSolicitudProveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonSolicitudProveedores.setText("Solicitud a Proveedores");
        BotonSolicitudProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSolicitudProveedoresActionPerformed(evt);
            }
        });

        BotonApartados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonApartados.setText("Apartados");
        BotonApartados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonApartadosActionPerformed(evt);
            }
        });

        BotonAbono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonAbono.setText("Abonos");
        BotonAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAbonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTiendaLayout = new javax.swing.GroupLayout(PanelTienda);
        PanelTienda.setLayout(PanelTiendaLayout);
        PanelTiendaLayout.setHorizontalGroup(
            PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTiendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTiendaLayout.createSequentialGroup()
                        .addComponent(BotonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonEliminar))
                    .addGroup(PanelTiendaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(BotonGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(BotonImprimir)))
                .addGap(293, 293, 293))
            .addGroup(PanelTiendaLayout.createSequentialGroup()
                .addGroup(PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTiendaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FrameTienda)
                            .addGroup(PanelTiendaLayout.createSequentialGroup()
                                .addComponent(BotonDashboard)
                                .addGap(18, 18, 18)
                                .addComponent(BotonClientes)
                                .addGap(18, 18, 18)
                                .addComponent(BotonProveedores)
                                .addGap(18, 18, 18)
                                .addComponent(BotonColaboradores)
                                .addGap(18, 18, 18)
                                .addComponent(BotonProductos)
                                .addGap(18, 18, 18)
                                .addComponent(BotonFactura)
                                .addGap(18, 18, 18)
                                .addComponent(BotonTienda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonPedidoEntreTiendas)
                                .addGap(49, 49, 49)
                                .addComponent(LabelUsuario))))
                    .addGroup(PanelTiendaLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(BotonSolicitudProveedores)
                        .addGap(18, 18, 18)
                        .addComponent(BotonApartados)
                        .addGap(18, 18, 18)
                        .addComponent(BotonAbono))
                    .addGroup(PanelTiendaLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PanelTiendaLayout.createSequentialGroup()
                                .addComponent(LabelIDDireccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextFieldIDDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelTiendaLayout.createSequentialGroup()
                                .addComponent(LabelIDTienda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextFieldIDTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelTiendaLayout.createSequentialGroup()
                                .addComponent(LabelIDColaborador)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldIDColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        PanelTiendaLayout.setVerticalGroup(
            PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTiendaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(FrameTienda)
                .addGap(18, 18, 18)
                .addGroup(PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonDashboard)
                    .addComponent(BotonClientes)
                    .addComponent(BotonProveedores)
                    .addComponent(BotonColaboradores)
                    .addComponent(BotonProductos)
                    .addComponent(BotonFactura)
                    .addComponent(BotonTienda)
                    .addComponent(BotonPedidoEntreTiendas)
                    .addComponent(LabelUsuario))
                .addGap(27, 27, 27)
                .addGroup(PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSolicitudProveedores)
                    .addComponent(BotonApartados)
                    .addComponent(BotonAbono))
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIDTienda)
                    .addComponent(TextFieldIDTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIDColaborador)
                    .addComponent(TextFieldIDColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIDDireccion)
                    .addComponent(TextFieldIDDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGuardar)
                    .addComponent(BotonImprimir))
                .addGap(18, 18, 18)
                .addGroup(PanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregar)
                    .addComponent(BotonModificar)
                    .addComponent(BotonEliminar))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPedidoEntreTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPedidoEntreTiendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPedidoEntreTiendasActionPerformed

    private void BotonTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonTiendaActionPerformed

    private void BotonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonFacturaActionPerformed

    private void BotonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDashboardActionPerformed
        this.frameDashboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonDashboardActionPerformed

    private void BotonSolicitudProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSolicitudProveedoresActionPerformed
       
    }//GEN-LAST:event_BotonSolicitudProveedoresActionPerformed

    private void BotonApartadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonApartadosActionPerformed
        
    }//GEN-LAST:event_BotonApartadosActionPerformed

    private void BotonAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAbonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAbonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAbono;
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonApartados;
    private javax.swing.JButton BotonClientes;
    private javax.swing.JButton BotonColaboradores;
    private javax.swing.JButton BotonDashboard;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonFactura;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonImprimir;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton BotonPedidoEntreTiendas;
    private javax.swing.JButton BotonProductos;
    private javax.swing.JButton BotonProveedores;
    private javax.swing.JButton BotonSolicitudProveedores;
    private javax.swing.JButton BotonTienda;
    private javax.swing.JLabel FrameTienda;
    private javax.swing.JLabel LabelIDColaborador;
    private javax.swing.JLabel LabelIDDireccion;
    private javax.swing.JLabel LabelIDTienda;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPanel PanelTienda;
    private javax.swing.JTextField TextFieldIDColaborador;
    private javax.swing.JTextField TextFieldIDDireccion;
    private javax.swing.JTextField TextFieldIDTienda;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
