package pdv_dall;

import BD.BDUsuario;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daniela
 */
public class FrameColaboradores extends javax.swing.JFrame {

    /**
     * Creates new form FrameColaboradores
     */
    FrameDashboard frameDashboard;
    
    public FrameColaboradores() {
        initComponents();
        refrescarTabla();
    }

    public void setDashboardFrame(FrameDashboard frameDashboard){
        this.frameDashboard = frameDashboard;
    }
    
    private void refrescarTabla(){
        BDUsuario conexion = new BDUsuario();
        conexion.llenarTabla(tablaUsuario);
        conexion.cerrarConexion();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FrameColaboradores = new javax.swing.JLabel();
        LabelIDColaborador = new javax.swing.JLabel();
        LabelNombreColaborador = new javax.swing.JLabel();
        LabelPrimerApellido = new javax.swing.JLabel();
        LabelSegundoApellido = new javax.swing.JLabel();
        LabelCedula = new javax.swing.JLabel();
        TextFieldIDColaborador = new javax.swing.JTextField();
        TextFieldNombreColaborador = new javax.swing.JTextField();
        TextFieldPrimerApellido = new javax.swing.JTextField();
        TextFieldSegundoApellido = new javax.swing.JTextField();
        TextFieldNumeroCedula = new javax.swing.JTextField();
        LabelFecha = new javax.swing.JLabel();
        TextFieldFecha = new javax.swing.JTextField();
        LabelIDRol = new javax.swing.JLabel();
        TextFieldTelefono = new javax.swing.JTextField();
        LabelIDDireccion = new javax.swing.JLabel();
        TextFieldIDDireccion = new javax.swing.JTextField();
        LabelTelefono = new javax.swing.JLabel();
        TextFieldIDRol = new javax.swing.JTextField();
        LabelIDLogin = new javax.swing.JLabel();
        TextFieldIDLogin = new javax.swing.JTextField();
        BotonAceptar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonAgregar = new javax.swing.JButton();
        BotonDashboard = new javax.swing.JButton();
        BotonClientes = new javax.swing.JButton();
        BotonProveedores = new javax.swing.JButton();
        BotonColaboradores = new javax.swing.JButton();
        BotonProductos = new javax.swing.JButton();
        BotonFacturas = new javax.swing.JButton();
        BotonTienda = new javax.swing.JButton();
        BotonPedidos = new javax.swing.JButton();
        LabelUsuario = new javax.swing.JLabel();
        BotonSolicitudProveedores = new javax.swing.JButton();
        BotonApartados = new javax.swing.JButton();
        BotonAbono = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        LabelIDDireccion1 = new javax.swing.JLabel();
        TextFieldIDDireccion1 = new javax.swing.JTextField();
        LabelIDDireccion2 = new javax.swing.JLabel();
        TextFieldIDDireccion2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1150, 600));

        FrameColaboradores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FrameColaboradores.setText("Colaboradores");

        LabelIDColaborador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIDColaborador.setText("ID Colaborador");

        LabelNombreColaborador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelNombreColaborador.setText("Nombre del Colaborador");

        LabelPrimerApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelPrimerApellido.setText("Primer Apellido");

        LabelSegundoApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelSegundoApellido.setText("Segundo Apellido");

        LabelCedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelCedula.setText("Número de Cédula");

        TextFieldIDColaborador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TextFieldNombreColaborador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TextFieldPrimerApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TextFieldSegundoApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TextFieldNumeroCedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LabelFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelFecha.setText("Fecha");

        TextFieldFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LabelIDRol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIDRol.setText("ID Rol");

        TextFieldTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LabelIDDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIDDireccion.setText("Provincia");

        TextFieldIDDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LabelTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelTelefono.setText("Teléfono");

        TextFieldIDRol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LabelIDLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIDLogin.setText("Contraseña");

        TextFieldIDLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        BotonAceptar.setBackground(new java.awt.Color(255, 153, 51));
        BotonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        BotonAceptar.setText("Aceptar");

        BotonCancelar.setBackground(new java.awt.Color(153, 0, 153));
        BotonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BotonCancelar.setText("Cancelar");

        BotonEliminar.setBackground(new java.awt.Color(255, 0, 51));
        BotonEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BotonEliminar.setText("Eliminar");
        BotonEliminar.setRolloverEnabled(false);

        BotonModificar.setBackground(new java.awt.Color(0, 153, 204));
        BotonModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonModificar.setForeground(new java.awt.Color(255, 255, 255));
        BotonModificar.setText("Modificar");
        BotonModificar.setRolloverEnabled(false);

        BotonAgregar.setBackground(new java.awt.Color(0, 204, 102));
        BotonAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BotonAgregar.setText("Agregar");

        BotonDashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonDashboard.setText("Dashboard");
        BotonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDashboardActionPerformed(evt);
            }
        });

        BotonClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonClientes.setText("Clientes");
        BotonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonClientesActionPerformed(evt);
            }
        });

        BotonProveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonProveedores.setText("Proveedores");

        BotonColaboradores.setBackground(new java.awt.Color(153, 153, 153));
        BotonColaboradores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonColaboradores.setText("Colaboradores");

        BotonProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonProductos.setText("Productos");

        BotonFacturas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonFacturas.setText("Facturas");

        BotonTienda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonTienda.setText("Tienda");

        BotonPedidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonPedidos.setText("Pedidos entre tiendas");
        BotonPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPedidosActionPerformed(evt);
            }
        });

        LabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelUsuario.setText("Usuario");

        BotonSolicitudProveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonSolicitudProveedores.setText("Solicitud a Proveedores");
        BotonSolicitudProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSolicitudProveedoresActionPerformed(evt);
            }
        });

        BotonApartados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonApartados.setText("Apartados");
        BotonApartados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonApartadosActionPerformed(evt);
            }
        });

        BotonAbono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonAbono.setText("Abonos");
        BotonAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAbonoActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        LabelIDDireccion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIDDireccion1.setText("Cantón");

        TextFieldIDDireccion1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LabelIDDireccion2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIDDireccion2.setText("Distrito");

        TextFieldIDDireccion2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuario);

        jLabel1.setText("Lista de usuarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(BotonDashboard)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonSolicitudProveedores)
                                .addGap(18, 18, 18)
                                .addComponent(BotonApartados)
                                .addGap(18, 18, 18)
                                .addComponent(BotonAbono))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonClientes)
                                .addGap(18, 18, 18)
                                .addComponent(BotonProveedores)
                                .addGap(18, 18, 18)
                                .addComponent(BotonColaboradores)
                                .addGap(16, 16, 16)
                                .addComponent(BotonProductos)
                                .addGap(18, 18, 18)
                                .addComponent(BotonFacturas)
                                .addGap(18, 18, 18)
                                .addComponent(BotonTienda)
                                .addGap(18, 18, 18)
                                .addComponent(BotonPedidos)
                                .addGap(48, 48, 48)
                                .addComponent(LabelUsuario))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(BotonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(FrameColaboradores)
                        .addGap(0, 1039, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCedula)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelIDColaborador)
                                    .addComponent(LabelNombreColaborador)
                                    .addComponent(LabelPrimerApellido)
                                    .addComponent(LabelSegundoApellido)
                                    .addComponent(LabelIDLogin))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextFieldPrimerApellido)
                                    .addComponent(TextFieldSegundoApellido)
                                    .addComponent(TextFieldNumeroCedula)
                                    .addComponent(TextFieldNombreColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(TextFieldIDColaborador)
                                    .addComponent(TextFieldIDLogin))))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LabelIDRol)
                                        .addGap(33, 33, 33)
                                        .addComponent(TextFieldIDRol, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LabelIDDireccion1)
                                        .addGap(28, 28, 28)
                                        .addComponent(TextFieldIDDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(LabelFecha)
                                            .addGap(39, 39, 39)
                                            .addComponent(TextFieldFecha))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(LabelIDDireccion2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TextFieldIDDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(LabelIDDireccion)
                                            .addGap(18, 18, 18)
                                            .addComponent(TextFieldIDDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(BotonAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(243, 243, 243))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FrameColaboradores)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonDashboard)
                    .addComponent(BotonClientes)
                    .addComponent(BotonProveedores)
                    .addComponent(BotonColaboradores)
                    .addComponent(BotonProductos)
                    .addComponent(BotonFacturas)
                    .addComponent(BotonTienda)
                    .addComponent(LabelUsuario)
                    .addComponent(BotonPedidos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonApartados)
                    .addComponent(BotonAbono)
                    .addComponent(BotonSolicitudProveedores))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelIDColaborador)
                            .addComponent(TextFieldIDColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNombreColaborador)
                            .addComponent(TextFieldNombreColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPrimerApellido)
                            .addComponent(TextFieldPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelSegundoApellido)
                            .addComponent(TextFieldSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCedula)
                            .addComponent(TextFieldNumeroCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelIDLogin)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextFieldIDLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelFecha)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonAgregar)
                            .addComponent(BotonModificar)
                            .addComponent(BotonEliminar)
                            .addComponent(BotonCancelar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTelefono)
                            .addComponent(TextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAceptar)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelIDRol)
                                    .addComponent(TextFieldIDRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelIDDireccion)
                                    .addComponent(TextFieldIDDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelIDDireccion1)
                                    .addComponent(TextFieldIDDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelIDDireccion2)
                                    .addComponent(TextFieldIDDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDashboardActionPerformed
        this.frameDashboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonDashboardActionPerformed

    private void BotonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonClientesActionPerformed

    private void BotonPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPedidosActionPerformed

    private void BotonSolicitudProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSolicitudProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSolicitudProveedoresActionPerformed

    private void BotonApartadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonApartadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonApartadosActionPerformed

    private void BotonAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAbonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAbonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameColaboradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAbono;
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonApartados;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonClientes;
    private javax.swing.JButton BotonColaboradores;
    private javax.swing.JButton BotonDashboard;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonFacturas;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton BotonPedidos;
    private javax.swing.JButton BotonProductos;
    private javax.swing.JButton BotonProveedores;
    private javax.swing.JButton BotonSolicitudProveedores;
    private javax.swing.JButton BotonTienda;
    private javax.swing.JLabel FrameColaboradores;
    private javax.swing.JLabel LabelCedula;
    private javax.swing.JLabel LabelFecha;
    private javax.swing.JLabel LabelIDColaborador;
    private javax.swing.JLabel LabelIDDireccion;
    private javax.swing.JLabel LabelIDDireccion1;
    private javax.swing.JLabel LabelIDDireccion2;
    private javax.swing.JLabel LabelIDLogin;
    private javax.swing.JLabel LabelIDRol;
    private javax.swing.JLabel LabelNombreColaborador;
    private javax.swing.JLabel LabelPrimerApellido;
    private javax.swing.JLabel LabelSegundoApellido;
    private javax.swing.JLabel LabelTelefono;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JTextField TextFieldFecha;
    private javax.swing.JTextField TextFieldIDColaborador;
    private javax.swing.JTextField TextFieldIDDireccion;
    private javax.swing.JTextField TextFieldIDDireccion1;
    private javax.swing.JTextField TextFieldIDDireccion2;
    private javax.swing.JTextField TextFieldIDLogin;
    private javax.swing.JTextField TextFieldIDRol;
    private javax.swing.JTextField TextFieldNombreColaborador;
    private javax.swing.JTextField TextFieldNumeroCedula;
    private javax.swing.JTextField TextFieldPrimerApellido;
    private javax.swing.JTextField TextFieldSegundoApellido;
    private javax.swing.JTextField TextFieldTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaUsuario;
    // End of variables declaration//GEN-END:variables
}
