package pdv_dall;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LINSEY A.G
 */
public class Tabla_Movimientos extends javax.swing.JFrame {

    
    
   
    
    /**
     * Creates new form Tabla_Movimientos
     */
    FrameDashboard frameDashboard;
    public Tabla_Movimientos() {
        initComponents();
    }
    public void setDashboardFrame(FrameDashboard frameDashboard){
        this.frameDashboard = frameDashboard;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPedidos = new javax.swing.JPanel();
        LabelCodigoTiendaOrigen = new javax.swing.JLabel();
        TextFieldCodigoTiendaOrigen = new javax.swing.JTextField();
        LabelNombreProducto = new javax.swing.JLabel();
        TextFieldNombreProducto = new javax.swing.JTextField();
        LabelPrecioUnitario = new javax.swing.JLabel();
        TextFieldPrecioUnitario = new javax.swing.JTextField();
        LabelCantidadSolicitada = new javax.swing.JLabel();
        TextFieldCantidadSolicitada = new javax.swing.JTextField();
        TextFieldProveedor = new javax.swing.JTextField();
        LabelProveedor = new javax.swing.JLabel();
        LabelFechaSolicitud = new javax.swing.JLabel();
        TextFieldFechaSolicitud = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPedidosentreTiendas = new javax.swing.JTable();
        BotonAgregar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        LabelCodigoTiendaDestino = new javax.swing.JLabel();
        TextFieldCodigoTiendaDestino = new javax.swing.JTextField();
        LabelNombreTiendaOrigen = new javax.swing.JLabel();
        TextFieldNombreTiendaOrigen = new javax.swing.JTextField();
        LabelNombreTiendaDestini = new javax.swing.JLabel();
        TextFieldNombreTiendaDestino = new javax.swing.JTextField();
        LabelTablaPedidos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        LabelNumeroPedido = new javax.swing.JLabel();
        TextFieldNumeroPedido = new javax.swing.JTextField();
        BotonDashboard = new javax.swing.JButton();
        BotonClientes = new javax.swing.JButton();
        BotonProveedores = new javax.swing.JButton();
        BotonProductos = new javax.swing.JButton();
        BotonFacturas = new javax.swing.JButton();
        BotonPedidos = new javax.swing.JButton();
        BotonColaboradores = new javax.swing.JButton();
        BotonTienda = new javax.swing.JButton();
        LabelUsuario = new javax.swing.JLabel();
        FramePedidos = new javax.swing.JLabel();
        BotonAbono = new javax.swing.JButton();
        BotonApartados = new javax.swing.JButton();
        BotonSolicitudProveedores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPedidos.setForeground(new java.awt.Color(204, 204, 204));
        PanelPedidos.setPreferredSize(new java.awt.Dimension(1150, 600));

        LabelCodigoTiendaOrigen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelCodigoTiendaOrigen.setText("Código de la tienda de orígen");

        TextFieldCodigoTiendaOrigen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldCodigoTiendaOrigen.setText("jTextField1");

        LabelNombreProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelNombreProducto.setText("Nombre del producto");

        TextFieldNombreProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldNombreProducto.setText("jTextField1");
        TextFieldNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreProductoActionPerformed(evt);
            }
        });

        LabelPrecioUnitario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelPrecioUnitario.setText("Precio Unitario");

        TextFieldPrecioUnitario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldPrecioUnitario.setText("jTextField1");

        LabelCantidadSolicitada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelCantidadSolicitada.setText("Cantidad solicitada");

        TextFieldCantidadSolicitada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldCantidadSolicitada.setText("jTextField1");

        TextFieldProveedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldProveedor.setText("jTextField1");

        LabelProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelProveedor.setText("Proveedor");

        LabelFechaSolicitud.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelFechaSolicitud.setText("Fecha de la solicitud");

        TextFieldFechaSolicitud.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldFechaSolicitud.setText("jTextField1");

        TablaPedidosentreTiendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Número de pedido", "Nombre del producto", "Cantidad Solicitada", "Precio Unitario", "Proveedor", "Nombre de la tienda de destino", "Codigo de la tienda de destino", "Nombre de la tienda de origen", "Codigo de la tienda de origen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaPedidosentreTiendas);

        BotonAgregar.setBackground(new java.awt.Color(51, 102, 0));
        BotonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonModificar.setBackground(new java.awt.Color(51, 51, 255));
        BotonModificar.setForeground(new java.awt.Color(255, 255, 255));
        BotonModificar.setText("Modificar");

        BotonEliminar.setBackground(new java.awt.Color(255, 0, 0));
        BotonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BotonEliminar.setText("Eliminar");

        LabelCodigoTiendaDestino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelCodigoTiendaDestino.setText("Código de la tienda destino");

        TextFieldCodigoTiendaDestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldCodigoTiendaDestino.setText("jTextField1");

        LabelNombreTiendaOrigen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelNombreTiendaOrigen.setText("Nombre de la tienda orígen");

        TextFieldNombreTiendaOrigen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldNombreTiendaOrigen.setText("jTextField1");

        LabelNombreTiendaDestini.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelNombreTiendaDestini.setText("Nombre de la tienda de destino");

        TextFieldNombreTiendaDestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldNombreTiendaDestino.setText("jTextField1");

        LabelTablaPedidos.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        LabelTablaPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTablaPedidos.setText("TABLA DE PEDIDOS");
        LabelTablaPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LabelTablaPedidos.setMaximumSize(new java.awt.Dimension(121, 14));
        LabelTablaPedidos.setPreferredSize(new java.awt.Dimension(121, 14));

        LabelNumeroPedido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelNumeroPedido.setText("Número de Pedido");

        TextFieldNumeroPedido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldNumeroPedido.setText("jTextField1");

        BotonDashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonDashboard.setText("Dashboard");
        BotonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDashboardActionPerformed(evt);
            }
        });

        BotonClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonClientes.setText("Clientes");

        BotonProveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonProveedores.setText("Proveedores");

        BotonProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonProductos.setText("Productos");

        BotonFacturas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonFacturas.setText("Facturas");
        BotonFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFacturasActionPerformed(evt);
            }
        });

        BotonPedidos.setBackground(new java.awt.Color(153, 153, 153));
        BotonPedidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonPedidos.setText("Pedidos entre tiendas");
        BotonPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPedidosActionPerformed(evt);
            }
        });

        BotonColaboradores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonColaboradores.setText("Colaboradores");
        BotonColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonColaboradoresActionPerformed(evt);
            }
        });

        BotonTienda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonTienda.setText("Tienda");

        LabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelUsuario.setText("Usuario");

        FramePedidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FramePedidos.setText("Pedidos entre Tiendas");

        BotonAbono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonAbono.setText("Abonos");
        BotonAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAbonoActionPerformed(evt);
            }
        });

        BotonApartados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonApartados.setText("Apartados");
        BotonApartados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonApartadosActionPerformed(evt);
            }
        });

        BotonSolicitudProveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonSolicitudProveedores.setText("Solicitud a Proveedores");
        BotonSolicitudProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSolicitudProveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPedidosLayout = new javax.swing.GroupLayout(PanelPedidos);
        PanelPedidos.setLayout(PanelPedidosLayout);
        PanelPedidosLayout.setHorizontalGroup(
            PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(PanelPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPedidosLayout.createSequentialGroup()
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator1)
                            .addGroup(PanelPedidosLayout.createSequentialGroup()
                                .addComponent(BotonAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonEliminar)
                                .addGap(172, 172, 172)
                                .addComponent(LabelTablaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 421, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(PanelPedidosLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCodigoTiendaDestino)
                            .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(PanelPedidosLayout.createSequentialGroup()
                                    .addComponent(LabelNumeroPedido)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelPedidosLayout.createSequentialGroup()
                                    .addComponent(LabelCodigoTiendaOrigen)
                                    .addGap(18, 18, 18)
                                    .addComponent(TextFieldCodigoTiendaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TextFieldCodigoTiendaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPedidosLayout.createSequentialGroup()
                                .addComponent(LabelNombreTiendaOrigen)
                                .addGap(33, 33, 33)
                                .addComponent(TextFieldNombreTiendaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPedidosLayout.createSequentialGroup()
                                .addComponent(LabelNombreTiendaDestini)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldNombreTiendaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelPrecioUnitario)
                            .addComponent(LabelCantidadSolicitada)
                            .addGroup(PanelPedidosLayout.createSequentialGroup()
                                .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelProveedor)
                                    .addComponent(LabelNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldCantidadSolicitada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelPedidosLayout.createSequentialGroup()
                                        .addComponent(LabelFechaSolicitud)
                                        .addGap(18, 18, 18)
                                        .addComponent(TextFieldFechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(87, 87, 87))))
            .addGroup(PanelPedidosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FramePedidos)
                    .addGroup(PanelPedidosLayout.createSequentialGroup()
                        .addComponent(BotonDashboard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPedidosLayout.createSequentialGroup()
                                .addComponent(BotonSolicitudProveedores)
                                .addGap(18, 18, 18)
                                .addComponent(BotonApartados)
                                .addGap(18, 18, 18)
                                .addComponent(BotonAbono))
                            .addGroup(PanelPedidosLayout.createSequentialGroup()
                                .addComponent(BotonClientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonProveedores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonColaboradores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonFacturas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonTienda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonPedidos)
                                .addGap(120, 120, 120)
                                .addComponent(LabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        PanelPedidosLayout.setVerticalGroup(
            PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FramePedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonDashboard)
                    .addComponent(BotonClientes)
                    .addComponent(BotonProveedores)
                    .addComponent(BotonProductos)
                    .addComponent(BotonFacturas)
                    .addComponent(BotonPedidos)
                    .addComponent(BotonColaboradores)
                    .addComponent(BotonTienda)
                    .addComponent(LabelUsuario))
                .addGap(18, 18, 18)
                .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSolicitudProveedores)
                    .addComponent(BotonApartados)
                    .addComponent(BotonAbono))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelPedidosLayout.createSequentialGroup()
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNumeroPedido)
                            .addComponent(TextFieldNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCodigoTiendaOrigen)
                            .addComponent(TextFieldCodigoTiendaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNombreTiendaOrigen)
                            .addComponent(TextFieldNombreTiendaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCodigoTiendaDestino)
                            .addComponent(TextFieldCodigoTiendaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNombreTiendaDestini)
                            .addComponent(TextFieldNombreTiendaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelPedidosLayout.createSequentialGroup()
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelFechaSolicitud)
                            .addComponent(TextFieldFechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNombreProducto)
                            .addComponent(TextFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCantidadSolicitada)
                            .addComponent(TextFieldCantidadSolicitada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPrecioUnitario)
                            .addComponent(TextFieldPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelProveedor)
                            .addComponent(TextFieldProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregar)
                    .addComponent(BotonModificar)
                    .addComponent(BotonEliminar)
                    .addComponent(LabelTablaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreProductoActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void BotonFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonFacturasActionPerformed

    private void BotonPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPedidosActionPerformed
              
    }//GEN-LAST:event_BotonPedidosActionPerformed

    private void BotonColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonColaboradoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonColaboradoresActionPerformed

    private void BotonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDashboardActionPerformed
        this.frameDashboard.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_BotonDashboardActionPerformed

    private void BotonAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAbonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAbonoActionPerformed

    private void BotonApartadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonApartadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonApartadosActionPerformed

    private void BotonSolicitudProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSolicitudProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSolicitudProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla_Movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla_Movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla_Movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla_Movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla_Movimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAbono;
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonApartados;
    private javax.swing.JButton BotonClientes;
    private javax.swing.JButton BotonColaboradores;
    private javax.swing.JButton BotonDashboard;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonFacturas;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton BotonPedidos;
    private javax.swing.JButton BotonProductos;
    private javax.swing.JButton BotonProveedores;
    private javax.swing.JButton BotonSolicitudProveedores;
    private javax.swing.JButton BotonTienda;
    private javax.swing.JLabel FramePedidos;
    private javax.swing.JLabel LabelCantidadSolicitada;
    private javax.swing.JLabel LabelCodigoTiendaDestino;
    private javax.swing.JLabel LabelCodigoTiendaOrigen;
    private javax.swing.JLabel LabelFechaSolicitud;
    private javax.swing.JLabel LabelNombreProducto;
    private javax.swing.JLabel LabelNombreTiendaDestini;
    private javax.swing.JLabel LabelNombreTiendaOrigen;
    private javax.swing.JLabel LabelNumeroPedido;
    private javax.swing.JLabel LabelPrecioUnitario;
    private javax.swing.JLabel LabelProveedor;
    private javax.swing.JLabel LabelTablaPedidos;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPanel PanelPedidos;
    private javax.swing.JTable TablaPedidosentreTiendas;
    private javax.swing.JTextField TextFieldCantidadSolicitada;
    private javax.swing.JTextField TextFieldCodigoTiendaDestino;
    private javax.swing.JTextField TextFieldCodigoTiendaOrigen;
    private javax.swing.JTextField TextFieldFechaSolicitud;
    private javax.swing.JTextField TextFieldNombreProducto;
    private javax.swing.JTextField TextFieldNombreTiendaDestino;
    private javax.swing.JTextField TextFieldNombreTiendaOrigen;
    private javax.swing.JTextField TextFieldNumeroPedido;
    private javax.swing.JTextField TextFieldPrecioUnitario;
    private javax.swing.JTextField TextFieldProveedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
